/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	"fmt"

	v1 "github.com/appvia/hub-apis/pkg/apis/clusters/v1"
	configv1 "github.com/appvia/hub-apis/pkg/apis/config/v1"
	orgv1 "github.com/appvia/hub-apis/pkg/apis/org/v1"
	rbacv1 "github.com/appvia/hub-apis/pkg/apis/rbac/v1"
	storev1 "github.com/appvia/hub-apis/pkg/apis/store/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=clusters.hub.appvia.io, Version=v1
	case v1.SchemeGroupVersion.WithResource("credentialses"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Clusters().V1().Credentialses().Informer()}, nil
	case v1.SchemeGroupVersion.WithResource("kuberneteses"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Clusters().V1().Kuberneteses().Informer()}, nil

		// Group=config.hub.appvia.io, Version=v1
	case configv1.SchemeGroupVersion.WithResource("allocationlists"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Config().V1().AllocationLists().Informer()}, nil
	case configv1.SchemeGroupVersion.WithResource("bindinglists"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Config().V1().BindingLists().Informer()}, nil
	case configv1.SchemeGroupVersion.WithResource("classes"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Config().V1().Classes().Informer()}, nil

		// Group=org.hub.appvia.io, Version=v1
	case orgv1.SchemeGroupVersion.WithResource("teams"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Org().V1().Teams().Informer()}, nil
	case orgv1.SchemeGroupVersion.WithResource("teammemberships"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Org().V1().TeamMemberships().Informer()}, nil
	case orgv1.SchemeGroupVersion.WithResource("users"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Org().V1().Users().Informer()}, nil
	case orgv1.SchemeGroupVersion.WithResource("workspaces"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Org().V1().Workspaces().Informer()}, nil

		// Group=rbac.hub.appvia.io, Version=v1
	case rbacv1.SchemeGroupVersion.WithResource("bindings"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Rbac().V1().Bindings().Informer()}, nil
	case rbacv1.SchemeGroupVersion.WithResource("roles"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Rbac().V1().Roles().Informer()}, nil

		// Group=store.hub.appvia.io, Version=v1
	case storev1.SchemeGroupVersion.WithResource("entities"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Store().V1().Entities().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
