/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	configv1 "github.com/appvia/hub-apis/pkg/apis/config/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClassInstanceLists implements ClassInstanceListInterface
type FakeClassInstanceLists struct {
	Fake *FakeConfigV1
	ns   string
}

var classinstancelistsResource = schema.GroupVersionResource{Group: "config.hub.appvia.io", Version: "v1", Resource: "classinstancelists"}

var classinstancelistsKind = schema.GroupVersionKind{Group: "config.hub.appvia.io", Version: "v1", Kind: "ClassInstanceList"}

// Get takes name of the classInstanceList, and returns the corresponding classInstanceList object, and an error if there is any.
func (c *FakeClassInstanceLists) Get(name string, options v1.GetOptions) (result *configv1.ClassInstanceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(classinstancelistsResource, c.ns, name), &configv1.ClassInstanceList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.ClassInstanceList), err
}

// List takes label and field selectors, and returns the list of ClassInstanceLists that match those selectors.
func (c *FakeClassInstanceLists) List(opts v1.ListOptions) (result *configv1.ClassInstanceListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(classinstancelistsResource, classinstancelistsKind, c.ns, opts), &configv1.ClassInstanceListList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.ClassInstanceListList), err
}

// Watch returns a watch.Interface that watches the requested classInstanceLists.
func (c *FakeClassInstanceLists) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(classinstancelistsResource, c.ns, opts))

}

// Create takes the representation of a classInstanceList and creates it.  Returns the server's representation of the classInstanceList, and an error, if there is any.
func (c *FakeClassInstanceLists) Create(classInstanceList *configv1.ClassInstanceList) (result *configv1.ClassInstanceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(classinstancelistsResource, c.ns, classInstanceList), &configv1.ClassInstanceList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.ClassInstanceList), err
}

// Update takes the representation of a classInstanceList and updates it. Returns the server's representation of the classInstanceList, and an error, if there is any.
func (c *FakeClassInstanceLists) Update(classInstanceList *configv1.ClassInstanceList) (result *configv1.ClassInstanceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(classinstancelistsResource, c.ns, classInstanceList), &configv1.ClassInstanceList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.ClassInstanceList), err
}

// Delete takes name of the classInstanceList and deletes it. Returns an error if one occurs.
func (c *FakeClassInstanceLists) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(classinstancelistsResource, c.ns, name), &configv1.ClassInstanceList{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClassInstanceLists) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(classinstancelistsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &configv1.ClassInstanceListList{})
	return err
}

// Patch applies the patch and returns the patched classInstanceList.
func (c *FakeClassInstanceLists) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *configv1.ClassInstanceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(classinstancelistsResource, c.ns, name, pt, data, subresources...), &configv1.ClassInstanceList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.ClassInstanceList), err
}
