/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	configv1 "github.com/appvia/hub-apis/pkg/apis/config/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBindingLists implements BindingListInterface
type FakeBindingLists struct {
	Fake *FakeConfigV1
	ns   string
}

var bindinglistsResource = schema.GroupVersionResource{Group: "config.hub.appvia.io", Version: "v1", Resource: "bindinglists"}

var bindinglistsKind = schema.GroupVersionKind{Group: "config.hub.appvia.io", Version: "v1", Kind: "BindingList"}

// Get takes name of the bindingList, and returns the corresponding bindingList object, and an error if there is any.
func (c *FakeBindingLists) Get(name string, options v1.GetOptions) (result *configv1.BindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(bindinglistsResource, c.ns, name), &configv1.BindingList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.BindingList), err
}

// List takes label and field selectors, and returns the list of BindingLists that match those selectors.
func (c *FakeBindingLists) List(opts v1.ListOptions) (result *configv1.BindingListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(bindinglistsResource, bindinglistsKind, c.ns, opts), &configv1.BindingListList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.BindingListList), err
}

// Watch returns a watch.Interface that watches the requested bindingLists.
func (c *FakeBindingLists) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(bindinglistsResource, c.ns, opts))

}

// Create takes the representation of a bindingList and creates it.  Returns the server's representation of the bindingList, and an error, if there is any.
func (c *FakeBindingLists) Create(bindingList *configv1.BindingList) (result *configv1.BindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(bindinglistsResource, c.ns, bindingList), &configv1.BindingList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.BindingList), err
}

// Update takes the representation of a bindingList and updates it. Returns the server's representation of the bindingList, and an error, if there is any.
func (c *FakeBindingLists) Update(bindingList *configv1.BindingList) (result *configv1.BindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(bindinglistsResource, c.ns, bindingList), &configv1.BindingList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.BindingList), err
}

// Delete takes name of the bindingList and deletes it. Returns an error if one occurs.
func (c *FakeBindingLists) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(bindinglistsResource, c.ns, name), &configv1.BindingList{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBindingLists) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(bindinglistsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &configv1.BindingListList{})
	return err
}

// Patch applies the patch and returns the patched bindingList.
func (c *FakeBindingLists) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *configv1.BindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(bindinglistsResource, c.ns, name, pt, data, subresources...), &configv1.BindingList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.BindingList), err
}
