/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	configv1 "github.com/appvia/hub-apis/pkg/apis/config/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAllocations implements AllocationInterface
type FakeAllocations struct {
	Fake *FakeConfigV1
	ns   string
}

var allocationsResource = schema.GroupVersionResource{Group: "config.hub.appvia.io", Version: "v1", Resource: "allocations"}

var allocationsKind = schema.GroupVersionKind{Group: "config.hub.appvia.io", Version: "v1", Kind: "Allocation"}

// Get takes name of the allocation, and returns the corresponding allocation object, and an error if there is any.
func (c *FakeAllocations) Get(name string, options v1.GetOptions) (result *configv1.Allocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(allocationsResource, c.ns, name), &configv1.Allocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.Allocation), err
}

// List takes label and field selectors, and returns the list of Allocations that match those selectors.
func (c *FakeAllocations) List(opts v1.ListOptions) (result *configv1.AllocationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(allocationsResource, allocationsKind, c.ns, opts), &configv1.AllocationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &configv1.AllocationList{ListMeta: obj.(*configv1.AllocationList).ListMeta}
	for _, item := range obj.(*configv1.AllocationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested allocations.
func (c *FakeAllocations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(allocationsResource, c.ns, opts))

}

// Create takes the representation of a allocation and creates it.  Returns the server's representation of the allocation, and an error, if there is any.
func (c *FakeAllocations) Create(allocation *configv1.Allocation) (result *configv1.Allocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(allocationsResource, c.ns, allocation), &configv1.Allocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.Allocation), err
}

// Update takes the representation of a allocation and updates it. Returns the server's representation of the allocation, and an error, if there is any.
func (c *FakeAllocations) Update(allocation *configv1.Allocation) (result *configv1.Allocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(allocationsResource, c.ns, allocation), &configv1.Allocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.Allocation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAllocations) UpdateStatus(allocation *configv1.Allocation) (*configv1.Allocation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(allocationsResource, "status", c.ns, allocation), &configv1.Allocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.Allocation), err
}

// Delete takes name of the allocation and deletes it. Returns an error if one occurs.
func (c *FakeAllocations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(allocationsResource, c.ns, name), &configv1.Allocation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAllocations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(allocationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &configv1.AllocationList{})
	return err
}

// Patch applies the patch and returns the patched allocation.
func (c *FakeAllocations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *configv1.Allocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(allocationsResource, c.ns, name, pt, data, subresources...), &configv1.Allocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.Allocation), err
}
