/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	configv1 "github.com/appvia/hub-apis/pkg/apis/config/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAllocationLists implements AllocationListInterface
type FakeAllocationLists struct {
	Fake *FakeConfigV1
	ns   string
}

var allocationlistsResource = schema.GroupVersionResource{Group: "config.hub.appvia.io", Version: "v1", Resource: "allocationlists"}

var allocationlistsKind = schema.GroupVersionKind{Group: "config.hub.appvia.io", Version: "v1", Kind: "AllocationList"}

// Get takes name of the allocationList, and returns the corresponding allocationList object, and an error if there is any.
func (c *FakeAllocationLists) Get(name string, options v1.GetOptions) (result *configv1.AllocationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(allocationlistsResource, c.ns, name), &configv1.AllocationList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.AllocationList), err
}

// List takes label and field selectors, and returns the list of AllocationLists that match those selectors.
func (c *FakeAllocationLists) List(opts v1.ListOptions) (result *configv1.AllocationListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(allocationlistsResource, allocationlistsKind, c.ns, opts), &configv1.AllocationListList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.AllocationListList), err
}

// Watch returns a watch.Interface that watches the requested allocationLists.
func (c *FakeAllocationLists) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(allocationlistsResource, c.ns, opts))

}

// Create takes the representation of a allocationList and creates it.  Returns the server's representation of the allocationList, and an error, if there is any.
func (c *FakeAllocationLists) Create(allocationList *configv1.AllocationList) (result *configv1.AllocationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(allocationlistsResource, c.ns, allocationList), &configv1.AllocationList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.AllocationList), err
}

// Update takes the representation of a allocationList and updates it. Returns the server's representation of the allocationList, and an error, if there is any.
func (c *FakeAllocationLists) Update(allocationList *configv1.AllocationList) (result *configv1.AllocationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(allocationlistsResource, c.ns, allocationList), &configv1.AllocationList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.AllocationList), err
}

// Delete takes name of the allocationList and deletes it. Returns an error if one occurs.
func (c *FakeAllocationLists) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(allocationlistsResource, c.ns, name), &configv1.AllocationList{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAllocationLists) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(allocationlistsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &configv1.AllocationListList{})
	return err
}

// Patch applies the patch and returns the patched allocationList.
func (c *FakeAllocationLists) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *configv1.AllocationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(allocationlistsResource, c.ns, name, pt, data, subresources...), &configv1.AllocationList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*configv1.AllocationList), err
}
