/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// TeamListerExpansion allows custom methods to be added to
// TeamLister.
type TeamListerExpansion interface{}

// TeamMembershipListerExpansion allows custom methods to be added to
// TeamMembershipLister.
type TeamMembershipListerExpansion interface{}

// TeamMembershipNamespaceListerExpansion allows custom methods to be added to
// TeamMembershipNamespaceLister.
type TeamMembershipNamespaceListerExpansion interface{}

// UserListerExpansion allows custom methods to be added to
// UserLister.
type UserListerExpansion interface{}

// WorkspaceListerExpansion allows custom methods to be added to
// WorkspaceLister.
type WorkspaceListerExpansion interface{}

// WorkspaceNamespaceListerExpansion allows custom methods to be added to
// WorkspaceNamespaceLister.
type WorkspaceNamespaceListerExpansion interface{}
