/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/appvia/hub-apis/pkg/apis/config/v1"
	scheme "github.com/appvia/hub-apis/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AllocationListsGetter has a method to return a AllocationListInterface.
// A group's client should implement this interface.
type AllocationListsGetter interface {
	AllocationLists(namespace string) AllocationListInterface
}

// AllocationListInterface has methods to work with AllocationList resources.
type AllocationListInterface interface {
	Create(*v1.AllocationList) (*v1.AllocationList, error)
	Update(*v1.AllocationList) (*v1.AllocationList, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.AllocationList, error)
	List(opts metav1.ListOptions) (*v1.AllocationListList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AllocationList, err error)
	AllocationListExpansion
}

// allocationLists implements AllocationListInterface
type allocationLists struct {
	client rest.Interface
	ns     string
}

// newAllocationLists returns a AllocationLists
func newAllocationLists(c *ConfigV1Client, namespace string) *allocationLists {
	return &allocationLists{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the allocationList, and returns the corresponding allocationList object, and an error if there is any.
func (c *allocationLists) Get(name string, options metav1.GetOptions) (result *v1.AllocationList, err error) {
	result = &v1.AllocationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("allocationlists").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AllocationLists that match those selectors.
func (c *allocationLists) List(opts metav1.ListOptions) (result *v1.AllocationListList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AllocationListList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("allocationlists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested allocationLists.
func (c *allocationLists) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("allocationlists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a allocationList and creates it.  Returns the server's representation of the allocationList, and an error, if there is any.
func (c *allocationLists) Create(allocationList *v1.AllocationList) (result *v1.AllocationList, err error) {
	result = &v1.AllocationList{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("allocationlists").
		Body(allocationList).
		Do().
		Into(result)
	return
}

// Update takes the representation of a allocationList and updates it. Returns the server's representation of the allocationList, and an error, if there is any.
func (c *allocationLists) Update(allocationList *v1.AllocationList) (result *v1.AllocationList, err error) {
	result = &v1.AllocationList{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("allocationlists").
		Name(allocationList.Name).
		Body(allocationList).
		Do().
		Into(result)
	return
}

// Delete takes name of the allocationList and deletes it. Returns an error if one occurs.
func (c *allocationLists) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("allocationlists").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *allocationLists) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("allocationlists").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched allocationList.
func (c *allocationLists) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AllocationList, err error) {
	result = &v1.AllocationList{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("allocationlists").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
