/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/appvia/hub-apis/pkg/apis/config/v1"
	scheme "github.com/appvia/hub-apis/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AllocationsGetter has a method to return a AllocationInterface.
// A group's client should implement this interface.
type AllocationsGetter interface {
	Allocations(namespace string) AllocationInterface
}

// AllocationInterface has methods to work with Allocation resources.
type AllocationInterface interface {
	Create(*v1.Allocation) (*v1.Allocation, error)
	Update(*v1.Allocation) (*v1.Allocation, error)
	UpdateStatus(*v1.Allocation) (*v1.Allocation, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Allocation, error)
	List(opts metav1.ListOptions) (*v1.AllocationList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Allocation, err error)
	AllocationExpansion
}

// allocations implements AllocationInterface
type allocations struct {
	client rest.Interface
	ns     string
}

// newAllocations returns a Allocations
func newAllocations(c *ConfigV1Client, namespace string) *allocations {
	return &allocations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the allocation, and returns the corresponding allocation object, and an error if there is any.
func (c *allocations) Get(name string, options metav1.GetOptions) (result *v1.Allocation, err error) {
	result = &v1.Allocation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("allocations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Allocations that match those selectors.
func (c *allocations) List(opts metav1.ListOptions) (result *v1.AllocationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AllocationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("allocations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested allocations.
func (c *allocations) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("allocations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a allocation and creates it.  Returns the server's representation of the allocation, and an error, if there is any.
func (c *allocations) Create(allocation *v1.Allocation) (result *v1.Allocation, err error) {
	result = &v1.Allocation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("allocations").
		Body(allocation).
		Do().
		Into(result)
	return
}

// Update takes the representation of a allocation and updates it. Returns the server's representation of the allocation, and an error, if there is any.
func (c *allocations) Update(allocation *v1.Allocation) (result *v1.Allocation, err error) {
	result = &v1.Allocation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("allocations").
		Name(allocation.Name).
		Body(allocation).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *allocations) UpdateStatus(allocation *v1.Allocation) (result *v1.Allocation, err error) {
	result = &v1.Allocation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("allocations").
		Name(allocation.Name).
		SubResource("status").
		Body(allocation).
		Do().
		Into(result)
	return
}

// Delete takes name of the allocation and deletes it. Returns an error if one occurs.
func (c *allocations) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("allocations").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *allocations) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("allocations").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched allocation.
func (c *allocations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Allocation, err error) {
	result = &v1.Allocation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("allocations").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
