/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/appvia/hub-apis/pkg/apis/config/v1"
	scheme "github.com/appvia/hub-apis/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClassesGetter has a method to return a ClassInterface.
// A group's client should implement this interface.
type ClassesGetter interface {
	Classes() ClassInterface
}

// ClassInterface has methods to work with Class resources.
type ClassInterface interface {
	Create(*v1.Class) (*v1.Class, error)
	Update(*v1.Class) (*v1.Class, error)
	UpdateStatus(*v1.Class) (*v1.Class, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Class, error)
	List(opts metav1.ListOptions) (*v1.ClassList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Class, err error)
	ClassExpansion
}

// classes implements ClassInterface
type classes struct {
	client rest.Interface
}

// newClasses returns a Classes
func newClasses(c *ConfigV1Client) *classes {
	return &classes{
		client: c.RESTClient(),
	}
}

// Get takes name of the class, and returns the corresponding class object, and an error if there is any.
func (c *classes) Get(name string, options metav1.GetOptions) (result *v1.Class, err error) {
	result = &v1.Class{}
	err = c.client.Get().
		Resource("classes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Classes that match those selectors.
func (c *classes) List(opts metav1.ListOptions) (result *v1.ClassList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ClassList{}
	err = c.client.Get().
		Resource("classes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested classes.
func (c *classes) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("classes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a class and creates it.  Returns the server's representation of the class, and an error, if there is any.
func (c *classes) Create(class *v1.Class) (result *v1.Class, err error) {
	result = &v1.Class{}
	err = c.client.Post().
		Resource("classes").
		Body(class).
		Do().
		Into(result)
	return
}

// Update takes the representation of a class and updates it. Returns the server's representation of the class, and an error, if there is any.
func (c *classes) Update(class *v1.Class) (result *v1.Class, err error) {
	result = &v1.Class{}
	err = c.client.Put().
		Resource("classes").
		Name(class.Name).
		Body(class).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *classes) UpdateStatus(class *v1.Class) (result *v1.Class, err error) {
	result = &v1.Class{}
	err = c.client.Put().
		Resource("classes").
		Name(class.Name).
		SubResource("status").
		Body(class).
		Do().
		Into(result)
	return
}

// Delete takes name of the class and deletes it. Returns an error if one occurs.
func (c *classes) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("classes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *classes) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("classes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched class.
func (c *classes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Class, err error) {
	result = &v1.Class{}
	err = c.client.Patch(pt).
		Resource("classes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
