/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/gambol99/hub-apis/pkg/apis/config/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ClassLister helps list Classes.
type ClassLister interface {
	// List lists all Classes in the indexer.
	List(selector labels.Selector) (ret []*v1.Class, err error)
	// Get retrieves the Class from the index for a given name.
	Get(name string) (*v1.Class, error)
	ClassListerExpansion
}

// classLister implements the ClassLister interface.
type classLister struct {
	indexer cache.Indexer
}

// NewClassLister returns a new ClassLister.
func NewClassLister(indexer cache.Indexer) ClassLister {
	return &classLister{indexer: indexer}
}

// List lists all Classes in the indexer.
func (s *classLister) List(selector labels.Selector) (ret []*v1.Class, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.Class))
	})
	return ret, err
}

// Get retrieves the Class from the index for a given name.
func (s *classLister) Get(name string) (*v1.Class, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("class"), name)
	}
	return obj.(*v1.Class), nil
}
