/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	corev1 "github.com/appvia/hub-apis/pkg/apis/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOAuthProviders implements OAuthProviderInterface
type FakeOAuthProviders struct {
	Fake *FakeCoreV1
	ns   string
}

var oauthprovidersResource = schema.GroupVersionResource{Group: "core.hub.appvia.io", Version: "v1", Resource: "oauthproviders"}

var oauthprovidersKind = schema.GroupVersionKind{Group: "core.hub.appvia.io", Version: "v1", Kind: "OAuthProvider"}

// Get takes name of the oAuthProvider, and returns the corresponding oAuthProvider object, and an error if there is any.
func (c *FakeOAuthProviders) Get(name string, options v1.GetOptions) (result *corev1.OAuthProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(oauthprovidersResource, c.ns, name), &corev1.OAuthProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.OAuthProvider), err
}

// List takes label and field selectors, and returns the list of OAuthProviders that match those selectors.
func (c *FakeOAuthProviders) List(opts v1.ListOptions) (result *corev1.OAuthProviderList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(oauthprovidersResource, oauthprovidersKind, c.ns, opts), &corev1.OAuthProviderList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &corev1.OAuthProviderList{ListMeta: obj.(*corev1.OAuthProviderList).ListMeta}
	for _, item := range obj.(*corev1.OAuthProviderList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested oAuthProviders.
func (c *FakeOAuthProviders) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(oauthprovidersResource, c.ns, opts))

}

// Create takes the representation of a oAuthProvider and creates it.  Returns the server's representation of the oAuthProvider, and an error, if there is any.
func (c *FakeOAuthProviders) Create(oAuthProvider *corev1.OAuthProvider) (result *corev1.OAuthProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(oauthprovidersResource, c.ns, oAuthProvider), &corev1.OAuthProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.OAuthProvider), err
}

// Update takes the representation of a oAuthProvider and updates it. Returns the server's representation of the oAuthProvider, and an error, if there is any.
func (c *FakeOAuthProviders) Update(oAuthProvider *corev1.OAuthProvider) (result *corev1.OAuthProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(oauthprovidersResource, c.ns, oAuthProvider), &corev1.OAuthProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.OAuthProvider), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOAuthProviders) UpdateStatus(oAuthProvider *corev1.OAuthProvider) (*corev1.OAuthProvider, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(oauthprovidersResource, "status", c.ns, oAuthProvider), &corev1.OAuthProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.OAuthProvider), err
}

// Delete takes name of the oAuthProvider and deletes it. Returns an error if one occurs.
func (c *FakeOAuthProviders) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(oauthprovidersResource, c.ns, name), &corev1.OAuthProvider{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOAuthProviders) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(oauthprovidersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &corev1.OAuthProviderList{})
	return err
}

// Patch applies the patch and returns the patched oAuthProvider.
func (c *FakeOAuthProviders) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *corev1.OAuthProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(oauthprovidersResource, c.ns, name, pt, data, subresources...), &corev1.OAuthProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.OAuthProvider), err
}
