/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	corev1 "github.com/appvia/hub-apis/pkg/apis/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIDPClients implements IDPClientInterface
type FakeIDPClients struct {
	Fake *FakeCoreV1
	ns   string
}

var idpclientsResource = schema.GroupVersionResource{Group: "core.hub.appvia.io", Version: "v1", Resource: "idpclients"}

var idpclientsKind = schema.GroupVersionKind{Group: "core.hub.appvia.io", Version: "v1", Kind: "IDPClient"}

// Get takes name of the iDPClient, and returns the corresponding iDPClient object, and an error if there is any.
func (c *FakeIDPClients) Get(name string, options v1.GetOptions) (result *corev1.IDPClient, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(idpclientsResource, c.ns, name), &corev1.IDPClient{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.IDPClient), err
}

// List takes label and field selectors, and returns the list of IDPClients that match those selectors.
func (c *FakeIDPClients) List(opts v1.ListOptions) (result *corev1.IDPClientList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(idpclientsResource, idpclientsKind, c.ns, opts), &corev1.IDPClientList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &corev1.IDPClientList{ListMeta: obj.(*corev1.IDPClientList).ListMeta}
	for _, item := range obj.(*corev1.IDPClientList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested iDPClients.
func (c *FakeIDPClients) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(idpclientsResource, c.ns, opts))

}

// Create takes the representation of a iDPClient and creates it.  Returns the server's representation of the iDPClient, and an error, if there is any.
func (c *FakeIDPClients) Create(iDPClient *corev1.IDPClient) (result *corev1.IDPClient, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(idpclientsResource, c.ns, iDPClient), &corev1.IDPClient{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.IDPClient), err
}

// Update takes the representation of a iDPClient and updates it. Returns the server's representation of the iDPClient, and an error, if there is any.
func (c *FakeIDPClients) Update(iDPClient *corev1.IDPClient) (result *corev1.IDPClient, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(idpclientsResource, c.ns, iDPClient), &corev1.IDPClient{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.IDPClient), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIDPClients) UpdateStatus(iDPClient *corev1.IDPClient) (*corev1.IDPClient, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(idpclientsResource, "status", c.ns, iDPClient), &corev1.IDPClient{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.IDPClient), err
}

// Delete takes name of the iDPClient and deletes it. Returns an error if one occurs.
func (c *FakeIDPClients) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(idpclientsResource, c.ns, name), &corev1.IDPClient{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIDPClients) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(idpclientsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &corev1.IDPClientList{})
	return err
}

// Patch applies the patch and returns the patched iDPClient.
func (c *FakeIDPClients) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *corev1.IDPClient, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(idpclientsResource, c.ns, name, pt, data, subresources...), &corev1.IDPClient{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.IDPClient), err
}
