/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	corev1 "github.com/appvia/hub-apis/pkg/apis/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWebHooks implements WebHookInterface
type FakeWebHooks struct {
	Fake *FakeCoreV1
	ns   string
}

var webhooksResource = schema.GroupVersionResource{Group: "core.hub.appvia.io", Version: "v1", Resource: "webhooks"}

var webhooksKind = schema.GroupVersionKind{Group: "core.hub.appvia.io", Version: "v1", Kind: "WebHook"}

// Get takes name of the webHook, and returns the corresponding webHook object, and an error if there is any.
func (c *FakeWebHooks) Get(name string, options v1.GetOptions) (result *corev1.WebHook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(webhooksResource, c.ns, name), &corev1.WebHook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.WebHook), err
}

// List takes label and field selectors, and returns the list of WebHooks that match those selectors.
func (c *FakeWebHooks) List(opts v1.ListOptions) (result *corev1.WebHookList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(webhooksResource, webhooksKind, c.ns, opts), &corev1.WebHookList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &corev1.WebHookList{ListMeta: obj.(*corev1.WebHookList).ListMeta}
	for _, item := range obj.(*corev1.WebHookList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested webHooks.
func (c *FakeWebHooks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(webhooksResource, c.ns, opts))

}

// Create takes the representation of a webHook and creates it.  Returns the server's representation of the webHook, and an error, if there is any.
func (c *FakeWebHooks) Create(webHook *corev1.WebHook) (result *corev1.WebHook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(webhooksResource, c.ns, webHook), &corev1.WebHook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.WebHook), err
}

// Update takes the representation of a webHook and updates it. Returns the server's representation of the webHook, and an error, if there is any.
func (c *FakeWebHooks) Update(webHook *corev1.WebHook) (result *corev1.WebHook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(webhooksResource, c.ns, webHook), &corev1.WebHook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.WebHook), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWebHooks) UpdateStatus(webHook *corev1.WebHook) (*corev1.WebHook, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(webhooksResource, "status", c.ns, webHook), &corev1.WebHook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.WebHook), err
}

// Delete takes name of the webHook and deletes it. Returns an error if one occurs.
func (c *FakeWebHooks) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(webhooksResource, c.ns, name), &corev1.WebHook{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWebHooks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(webhooksResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &corev1.WebHookList{})
	return err
}

// Patch applies the patch and returns the patched webHook.
func (c *FakeWebHooks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *corev1.WebHook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(webhooksResource, c.ns, name, pt, data, subresources...), &corev1.WebHook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*corev1.WebHook), err
}
