/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/appvia/hub-apis/pkg/apis/org/v1"
	scheme "github.com/appvia/hub-apis/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TeamInvitationsGetter has a method to return a TeamInvitationInterface.
// A group's client should implement this interface.
type TeamInvitationsGetter interface {
	TeamInvitations(namespace string) TeamInvitationInterface
}

// TeamInvitationInterface has methods to work with TeamInvitation resources.
type TeamInvitationInterface interface {
	Create(*v1.TeamInvitation) (*v1.TeamInvitation, error)
	Update(*v1.TeamInvitation) (*v1.TeamInvitation, error)
	UpdateStatus(*v1.TeamInvitation) (*v1.TeamInvitation, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.TeamInvitation, error)
	List(opts metav1.ListOptions) (*v1.TeamInvitationList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.TeamInvitation, err error)
	TeamInvitationExpansion
}

// teamInvitations implements TeamInvitationInterface
type teamInvitations struct {
	client rest.Interface
	ns     string
}

// newTeamInvitations returns a TeamInvitations
func newTeamInvitations(c *OrgV1Client, namespace string) *teamInvitations {
	return &teamInvitations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the teamInvitation, and returns the corresponding teamInvitation object, and an error if there is any.
func (c *teamInvitations) Get(name string, options metav1.GetOptions) (result *v1.TeamInvitation, err error) {
	result = &v1.TeamInvitation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("teaminvitations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TeamInvitations that match those selectors.
func (c *teamInvitations) List(opts metav1.ListOptions) (result *v1.TeamInvitationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.TeamInvitationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("teaminvitations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested teamInvitations.
func (c *teamInvitations) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("teaminvitations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a teamInvitation and creates it.  Returns the server's representation of the teamInvitation, and an error, if there is any.
func (c *teamInvitations) Create(teamInvitation *v1.TeamInvitation) (result *v1.TeamInvitation, err error) {
	result = &v1.TeamInvitation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("teaminvitations").
		Body(teamInvitation).
		Do().
		Into(result)
	return
}

// Update takes the representation of a teamInvitation and updates it. Returns the server's representation of the teamInvitation, and an error, if there is any.
func (c *teamInvitations) Update(teamInvitation *v1.TeamInvitation) (result *v1.TeamInvitation, err error) {
	result = &v1.TeamInvitation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("teaminvitations").
		Name(teamInvitation.Name).
		Body(teamInvitation).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *teamInvitations) UpdateStatus(teamInvitation *v1.TeamInvitation) (result *v1.TeamInvitation, err error) {
	result = &v1.TeamInvitation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("teaminvitations").
		Name(teamInvitation.Name).
		SubResource("status").
		Body(teamInvitation).
		Do().
		Into(result)
	return
}

// Delete takes name of the teamInvitation and deletes it. Returns an error if one occurs.
func (c *teamInvitations) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("teaminvitations").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *teamInvitations) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("teaminvitations").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched teamInvitation.
func (c *teamInvitations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.TeamInvitation, err error) {
	result = &v1.TeamInvitation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("teaminvitations").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
