/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/appvia/hub-apis/pkg/apis/org/v1"
	scheme "github.com/appvia/hub-apis/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TeamMembershipsGetter has a method to return a TeamMembershipInterface.
// A group's client should implement this interface.
type TeamMembershipsGetter interface {
	TeamMemberships() TeamMembershipInterface
}

// TeamMembershipInterface has methods to work with TeamMembership resources.
type TeamMembershipInterface interface {
	Create(*v1.TeamMembership) (*v1.TeamMembership, error)
	Update(*v1.TeamMembership) (*v1.TeamMembership, error)
	UpdateStatus(*v1.TeamMembership) (*v1.TeamMembership, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.TeamMembership, error)
	List(opts metav1.ListOptions) (*v1.TeamMembershipList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.TeamMembership, err error)
	TeamMembershipExpansion
}

// teamMemberships implements TeamMembershipInterface
type teamMemberships struct {
	client rest.Interface
}

// newTeamMemberships returns a TeamMemberships
func newTeamMemberships(c *OrgV1Client) *teamMemberships {
	return &teamMemberships{
		client: c.RESTClient(),
	}
}

// Get takes name of the teamMembership, and returns the corresponding teamMembership object, and an error if there is any.
func (c *teamMemberships) Get(name string, options metav1.GetOptions) (result *v1.TeamMembership, err error) {
	result = &v1.TeamMembership{}
	err = c.client.Get().
		Resource("teammemberships").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TeamMemberships that match those selectors.
func (c *teamMemberships) List(opts metav1.ListOptions) (result *v1.TeamMembershipList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.TeamMembershipList{}
	err = c.client.Get().
		Resource("teammemberships").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested teamMemberships.
func (c *teamMemberships) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("teammemberships").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a teamMembership and creates it.  Returns the server's representation of the teamMembership, and an error, if there is any.
func (c *teamMemberships) Create(teamMembership *v1.TeamMembership) (result *v1.TeamMembership, err error) {
	result = &v1.TeamMembership{}
	err = c.client.Post().
		Resource("teammemberships").
		Body(teamMembership).
		Do().
		Into(result)
	return
}

// Update takes the representation of a teamMembership and updates it. Returns the server's representation of the teamMembership, and an error, if there is any.
func (c *teamMemberships) Update(teamMembership *v1.TeamMembership) (result *v1.TeamMembership, err error) {
	result = &v1.TeamMembership{}
	err = c.client.Put().
		Resource("teammemberships").
		Name(teamMembership.Name).
		Body(teamMembership).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *teamMemberships) UpdateStatus(teamMembership *v1.TeamMembership) (result *v1.TeamMembership, err error) {
	result = &v1.TeamMembership{}
	err = c.client.Put().
		Resource("teammemberships").
		Name(teamMembership.Name).
		SubResource("status").
		Body(teamMembership).
		Do().
		Into(result)
	return
}

// Delete takes name of the teamMembership and deletes it. Returns an error if one occurs.
func (c *teamMemberships) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("teammemberships").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *teamMemberships) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("teammemberships").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched teamMembership.
func (c *teamMemberships) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.TeamMembership, err error) {
	result = &v1.TeamMembership{}
	err = c.client.Patch(pt).
		Resource("teammemberships").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
