// +build !ignore_autogenerated

/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/appvia/hub-apis/pkg/apis/clusters/v1.Credentials":       schema_pkg_apis_clusters_v1_Credentials(ref),
		"github.com/appvia/hub-apis/pkg/apis/clusters/v1.CredentialsSpec":   schema_pkg_apis_clusters_v1_CredentialsSpec(ref),
		"github.com/appvia/hub-apis/pkg/apis/clusters/v1.CredentialsStatus": schema_pkg_apis_clusters_v1_CredentialsStatus(ref),
		"github.com/appvia/hub-apis/pkg/apis/clusters/v1.Kubernetes":        schema_pkg_apis_clusters_v1_Kubernetes(ref),
		"github.com/appvia/hub-apis/pkg/apis/clusters/v1.KubernetesSpec":    schema_pkg_apis_clusters_v1_KubernetesSpec(ref),
		"github.com/appvia/hub-apis/pkg/apis/clusters/v1.KubernetesStatus":  schema_pkg_apis_clusters_v1_KubernetesStatus(ref),
	}
}

func schema_pkg_apis_clusters_v1_Credentials(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Credentials is the Schema for the roles API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/appvia/hub-apis/pkg/apis/clusters/v1.CredentialsSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/appvia/hub-apis/pkg/apis/clusters/v1.CredentialsStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/appvia/hub-apis/pkg/apis/clusters/v1.CredentialsSpec", "github.com/appvia/hub-apis/pkg/apis/clusters/v1.CredentialsStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_clusters_v1_CredentialsSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CredentialsSpec defines the desired state of Credentials",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"caCertificate": {
						SchemaProps: spec.SchemaProps{
							Description: "CaCertificate is the base64 encoded cluster certificate",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"endpoint": {
						SchemaProps: spec.SchemaProps{
							Description: "Endpoint is the kubernetes endpoint url",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"token": {
						SchemaProps: spec.SchemaProps{
							Description: "Token is the hub-admin service account token which is bound to cluster-admin",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
				Required: []string{"caCertificate", "endpoint", "token"},
			},
		},
	}
}

func schema_pkg_apis_clusters_v1_CredentialsStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CredentialsStatus defines the observed state of Credentials",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_clusters_v1_Kubernetes(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Kubernetes is the Schema for the roles API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/appvia/hub-apis/pkg/apis/clusters/v1.KubernetesSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/appvia/hub-apis/pkg/apis/clusters/v1.KubernetesStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/appvia/hub-apis/pkg/apis/clusters/v1.KubernetesSpec", "github.com/appvia/hub-apis/pkg/apis/clusters/v1.KubernetesStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_clusters_v1_KubernetesSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KubernetesSpec defines the desired state of Cluster",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"ownership": {
						SchemaProps: spec.SchemaProps{
							Description: "Ownership is the cloud cluster provider type for this kubernetes",
							Ref:         ref("github.com/appvia/hub-apis/pkg/apis/config/v1.Ownership"),
						},
					},
					"caCertificate": {
						SchemaProps: spec.SchemaProps{
							Description: "CaCertificate is the base64 encoded cluster certificate",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"endpoint": {
						SchemaProps: spec.SchemaProps{
							Description: "Endpoint is the kubernetes endpoint url",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"token": {
						SchemaProps: spec.SchemaProps{
							Description: "Token is the hub-admin service account token which is bound to cluster-admin",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
				Required: []string{"ownership", "caCertificate", "endpoint", "token"},
			},
		},
		Dependencies: []string{
			"github.com/appvia/hub-apis/pkg/apis/config/v1.Ownership"},
	}
}

func schema_pkg_apis_clusters_v1_KubernetesStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KubernetesStatus defines the observed state of Cluster",
				Type:        []string{"object"},
			},
		},
	}
}
