/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clustersv1 "github.com/appvia/hub-apis/pkg/apis/clusters/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKuberneteses implements KubernetesInterface
type FakeKuberneteses struct {
	Fake *FakeClustersV1
	ns   string
}

var kubernetesesResource = schema.GroupVersionResource{Group: "clusters.compute.hub.appvia.io", Version: "v1", Resource: "kuberneteses"}

var kubernetesesKind = schema.GroupVersionKind{Group: "clusters.compute.hub.appvia.io", Version: "v1", Kind: "Kubernetes"}

// Get takes name of the kubernetes, and returns the corresponding kubernetes object, and an error if there is any.
func (c *FakeKuberneteses) Get(name string, options v1.GetOptions) (result *clustersv1.Kubernetes, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kubernetesesResource, c.ns, name), &clustersv1.Kubernetes{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clustersv1.Kubernetes), err
}

// List takes label and field selectors, and returns the list of Kuberneteses that match those selectors.
func (c *FakeKuberneteses) List(opts v1.ListOptions) (result *clustersv1.KubernetesList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kubernetesesResource, kubernetesesKind, c.ns, opts), &clustersv1.KubernetesList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &clustersv1.KubernetesList{ListMeta: obj.(*clustersv1.KubernetesList).ListMeta}
	for _, item := range obj.(*clustersv1.KubernetesList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kuberneteses.
func (c *FakeKuberneteses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kubernetesesResource, c.ns, opts))

}

// Create takes the representation of a kubernetes and creates it.  Returns the server's representation of the kubernetes, and an error, if there is any.
func (c *FakeKuberneteses) Create(kubernetes *clustersv1.Kubernetes) (result *clustersv1.Kubernetes, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kubernetesesResource, c.ns, kubernetes), &clustersv1.Kubernetes{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clustersv1.Kubernetes), err
}

// Update takes the representation of a kubernetes and updates it. Returns the server's representation of the kubernetes, and an error, if there is any.
func (c *FakeKuberneteses) Update(kubernetes *clustersv1.Kubernetes) (result *clustersv1.Kubernetes, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kubernetesesResource, c.ns, kubernetes), &clustersv1.Kubernetes{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clustersv1.Kubernetes), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKuberneteses) UpdateStatus(kubernetes *clustersv1.Kubernetes) (*clustersv1.Kubernetes, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kubernetesesResource, "status", c.ns, kubernetes), &clustersv1.Kubernetes{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clustersv1.Kubernetes), err
}

// Delete takes name of the kubernetes and deletes it. Returns an error if one occurs.
func (c *FakeKuberneteses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kubernetesesResource, c.ns, name), &clustersv1.Kubernetes{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKuberneteses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kubernetesesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &clustersv1.KubernetesList{})
	return err
}

// Patch applies the patch and returns the patched kubernetes.
func (c *FakeKuberneteses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *clustersv1.Kubernetes, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kubernetesesResource, c.ns, name, pt, data, subresources...), &clustersv1.Kubernetes{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clustersv1.Kubernetes), err
}
