/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clustersv1 "github.com/appvia/hub-apis/pkg/apis/clusters/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCredentialses implements CredentialsInterface
type FakeCredentialses struct {
	Fake *FakeClustersV1
	ns   string
}

var credentialsesResource = schema.GroupVersionResource{Group: "clusters.compute.hub.appvia.io", Version: "v1", Resource: "credentialses"}

var credentialsesKind = schema.GroupVersionKind{Group: "clusters.compute.hub.appvia.io", Version: "v1", Kind: "Credentials"}

// Get takes name of the credentials, and returns the corresponding credentials object, and an error if there is any.
func (c *FakeCredentialses) Get(name string, options v1.GetOptions) (result *clustersv1.Credentials, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(credentialsesResource, c.ns, name), &clustersv1.Credentials{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clustersv1.Credentials), err
}

// List takes label and field selectors, and returns the list of Credentialses that match those selectors.
func (c *FakeCredentialses) List(opts v1.ListOptions) (result *clustersv1.CredentialsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(credentialsesResource, credentialsesKind, c.ns, opts), &clustersv1.CredentialsList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &clustersv1.CredentialsList{ListMeta: obj.(*clustersv1.CredentialsList).ListMeta}
	for _, item := range obj.(*clustersv1.CredentialsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested credentialses.
func (c *FakeCredentialses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(credentialsesResource, c.ns, opts))

}

// Create takes the representation of a credentials and creates it.  Returns the server's representation of the credentials, and an error, if there is any.
func (c *FakeCredentialses) Create(credentials *clustersv1.Credentials) (result *clustersv1.Credentials, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(credentialsesResource, c.ns, credentials), &clustersv1.Credentials{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clustersv1.Credentials), err
}

// Update takes the representation of a credentials and updates it. Returns the server's representation of the credentials, and an error, if there is any.
func (c *FakeCredentialses) Update(credentials *clustersv1.Credentials) (result *clustersv1.Credentials, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(credentialsesResource, c.ns, credentials), &clustersv1.Credentials{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clustersv1.Credentials), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCredentialses) UpdateStatus(credentials *clustersv1.Credentials) (*clustersv1.Credentials, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(credentialsesResource, "status", c.ns, credentials), &clustersv1.Credentials{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clustersv1.Credentials), err
}

// Delete takes name of the credentials and deletes it. Returns an error if one occurs.
func (c *FakeCredentialses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(credentialsesResource, c.ns, name), &clustersv1.Credentials{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCredentialses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(credentialsesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &clustersv1.CredentialsList{})
	return err
}

// Patch applies the patch and returns the patched credentials.
func (c *FakeCredentialses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *clustersv1.Credentials, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(credentialsesResource, c.ns, name, pt, data, subresources...), &clustersv1.Credentials{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clustersv1.Credentials), err
}
