/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clustersv1 "github.com/gambol99/hub-apis/pkg/apis/clusters/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterCredentials implements ClusterCredentialInterface
type FakeClusterCredentials struct {
	Fake *FakeClustersV1
	ns   string
}

var clustercredentialsResource = schema.GroupVersionResource{Group: "clusters.hub.appvia.io", Version: "v1", Resource: "clustercredentials"}

var clustercredentialsKind = schema.GroupVersionKind{Group: "clusters.hub.appvia.io", Version: "v1", Kind: "ClusterCredential"}

// Get takes name of the clusterCredential, and returns the corresponding clusterCredential object, and an error if there is any.
func (c *FakeClusterCredentials) Get(name string, options v1.GetOptions) (result *clustersv1.ClusterCredential, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clustercredentialsResource, c.ns, name), &clustersv1.ClusterCredential{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clustersv1.ClusterCredential), err
}

// List takes label and field selectors, and returns the list of ClusterCredentials that match those selectors.
func (c *FakeClusterCredentials) List(opts v1.ListOptions) (result *clustersv1.ClusterCredentialList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clustercredentialsResource, clustercredentialsKind, c.ns, opts), &clustersv1.ClusterCredentialList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &clustersv1.ClusterCredentialList{ListMeta: obj.(*clustersv1.ClusterCredentialList).ListMeta}
	for _, item := range obj.(*clustersv1.ClusterCredentialList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterCredentials.
func (c *FakeClusterCredentials) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clustercredentialsResource, c.ns, opts))

}

// Create takes the representation of a clusterCredential and creates it.  Returns the server's representation of the clusterCredential, and an error, if there is any.
func (c *FakeClusterCredentials) Create(clusterCredential *clustersv1.ClusterCredential) (result *clustersv1.ClusterCredential, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clustercredentialsResource, c.ns, clusterCredential), &clustersv1.ClusterCredential{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clustersv1.ClusterCredential), err
}

// Update takes the representation of a clusterCredential and updates it. Returns the server's representation of the clusterCredential, and an error, if there is any.
func (c *FakeClusterCredentials) Update(clusterCredential *clustersv1.ClusterCredential) (result *clustersv1.ClusterCredential, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clustercredentialsResource, c.ns, clusterCredential), &clustersv1.ClusterCredential{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clustersv1.ClusterCredential), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterCredentials) UpdateStatus(clusterCredential *clustersv1.ClusterCredential) (*clustersv1.ClusterCredential, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(clustercredentialsResource, "status", c.ns, clusterCredential), &clustersv1.ClusterCredential{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clustersv1.ClusterCredential), err
}

// Delete takes name of the clusterCredential and deletes it. Returns an error if one occurs.
func (c *FakeClusterCredentials) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(clustercredentialsResource, c.ns, name), &clustersv1.ClusterCredential{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterCredentials) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clustercredentialsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &clustersv1.ClusterCredentialList{})
	return err
}

// Patch applies the patch and returns the patched clusterCredential.
func (c *FakeClusterCredentials) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *clustersv1.ClusterCredential, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clustercredentialsResource, c.ns, name, pt, data, subresources...), &clustersv1.ClusterCredential{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clustersv1.ClusterCredential), err
}
