/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/appvia/hub-apis/pkg/apis/core/v1"
	scheme "github.com/appvia/hub-apis/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IDPsGetter has a method to return a IDPInterface.
// A group's client should implement this interface.
type IDPsGetter interface {
	IDPs(namespace string) IDPInterface
}

// IDPInterface has methods to work with IDP resources.
type IDPInterface interface {
	Create(*v1.IDP) (*v1.IDP, error)
	Update(*v1.IDP) (*v1.IDP, error)
	UpdateStatus(*v1.IDP) (*v1.IDP, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.IDP, error)
	List(opts metav1.ListOptions) (*v1.IDPList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.IDP, err error)
	IDPExpansion
}

// iDPs implements IDPInterface
type iDPs struct {
	client rest.Interface
	ns     string
}

// newIDPs returns a IDPs
func newIDPs(c *CoreV1Client, namespace string) *iDPs {
	return &iDPs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the iDP, and returns the corresponding iDP object, and an error if there is any.
func (c *iDPs) Get(name string, options metav1.GetOptions) (result *v1.IDP, err error) {
	result = &v1.IDP{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("idps").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IDPs that match those selectors.
func (c *iDPs) List(opts metav1.ListOptions) (result *v1.IDPList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.IDPList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("idps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested iDPs.
func (c *iDPs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("idps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a iDP and creates it.  Returns the server's representation of the iDP, and an error, if there is any.
func (c *iDPs) Create(iDP *v1.IDP) (result *v1.IDP, err error) {
	result = &v1.IDP{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("idps").
		Body(iDP).
		Do().
		Into(result)
	return
}

// Update takes the representation of a iDP and updates it. Returns the server's representation of the iDP, and an error, if there is any.
func (c *iDPs) Update(iDP *v1.IDP) (result *v1.IDP, err error) {
	result = &v1.IDP{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("idps").
		Name(iDP.Name).
		Body(iDP).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *iDPs) UpdateStatus(iDP *v1.IDP) (result *v1.IDP, err error) {
	result = &v1.IDP{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("idps").
		Name(iDP.Name).
		SubResource("status").
		Body(iDP).
		Do().
		Into(result)
	return
}

// Delete takes name of the iDP and deletes it. Returns an error if one occurs.
func (c *iDPs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("idps").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *iDPs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("idps").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched iDP.
func (c *iDPs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.IDP, err error) {
	result = &v1.IDP{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("idps").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
