/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/appvia/hub-apis/pkg/apis/core/v1"
	scheme "github.com/appvia/hub-apis/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IDPClientsGetter has a method to return a IDPClientInterface.
// A group's client should implement this interface.
type IDPClientsGetter interface {
	IDPClients(namespace string) IDPClientInterface
}

// IDPClientInterface has methods to work with IDPClient resources.
type IDPClientInterface interface {
	Create(*v1.IDPClient) (*v1.IDPClient, error)
	Update(*v1.IDPClient) (*v1.IDPClient, error)
	UpdateStatus(*v1.IDPClient) (*v1.IDPClient, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.IDPClient, error)
	List(opts metav1.ListOptions) (*v1.IDPClientList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.IDPClient, err error)
	IDPClientExpansion
}

// iDPClients implements IDPClientInterface
type iDPClients struct {
	client rest.Interface
	ns     string
}

// newIDPClients returns a IDPClients
func newIDPClients(c *CoreV1Client, namespace string) *iDPClients {
	return &iDPClients{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the iDPClient, and returns the corresponding iDPClient object, and an error if there is any.
func (c *iDPClients) Get(name string, options metav1.GetOptions) (result *v1.IDPClient, err error) {
	result = &v1.IDPClient{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("idpclients").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IDPClients that match those selectors.
func (c *iDPClients) List(opts metav1.ListOptions) (result *v1.IDPClientList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.IDPClientList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("idpclients").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested iDPClients.
func (c *iDPClients) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("idpclients").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a iDPClient and creates it.  Returns the server's representation of the iDPClient, and an error, if there is any.
func (c *iDPClients) Create(iDPClient *v1.IDPClient) (result *v1.IDPClient, err error) {
	result = &v1.IDPClient{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("idpclients").
		Body(iDPClient).
		Do().
		Into(result)
	return
}

// Update takes the representation of a iDPClient and updates it. Returns the server's representation of the iDPClient, and an error, if there is any.
func (c *iDPClients) Update(iDPClient *v1.IDPClient) (result *v1.IDPClient, err error) {
	result = &v1.IDPClient{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("idpclients").
		Name(iDPClient.Name).
		Body(iDPClient).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *iDPClients) UpdateStatus(iDPClient *v1.IDPClient) (result *v1.IDPClient, err error) {
	result = &v1.IDPClient{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("idpclients").
		Name(iDPClient.Name).
		SubResource("status").
		Body(iDPClient).
		Do().
		Into(result)
	return
}

// Delete takes name of the iDPClient and deletes it. Returns an error if one occurs.
func (c *iDPClients) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("idpclients").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *iDPClients) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("idpclients").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched iDPClient.
func (c *iDPClients) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.IDPClient, err error) {
	result = &v1.IDPClient{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("idpclients").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
