/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/appvia/hub-apis/pkg/apis/core/v1"
	scheme "github.com/appvia/hub-apis/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// OAuthProvidersGetter has a method to return a OAuthProviderInterface.
// A group's client should implement this interface.
type OAuthProvidersGetter interface {
	OAuthProviders(namespace string) OAuthProviderInterface
}

// OAuthProviderInterface has methods to work with OAuthProvider resources.
type OAuthProviderInterface interface {
	Create(*v1.OAuthProvider) (*v1.OAuthProvider, error)
	Update(*v1.OAuthProvider) (*v1.OAuthProvider, error)
	UpdateStatus(*v1.OAuthProvider) (*v1.OAuthProvider, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.OAuthProvider, error)
	List(opts metav1.ListOptions) (*v1.OAuthProviderList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.OAuthProvider, err error)
	OAuthProviderExpansion
}

// oAuthProviders implements OAuthProviderInterface
type oAuthProviders struct {
	client rest.Interface
	ns     string
}

// newOAuthProviders returns a OAuthProviders
func newOAuthProviders(c *CoreV1Client, namespace string) *oAuthProviders {
	return &oAuthProviders{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the oAuthProvider, and returns the corresponding oAuthProvider object, and an error if there is any.
func (c *oAuthProviders) Get(name string, options metav1.GetOptions) (result *v1.OAuthProvider, err error) {
	result = &v1.OAuthProvider{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("oauthproviders").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of OAuthProviders that match those selectors.
func (c *oAuthProviders) List(opts metav1.ListOptions) (result *v1.OAuthProviderList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.OAuthProviderList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("oauthproviders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested oAuthProviders.
func (c *oAuthProviders) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("oauthproviders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a oAuthProvider and creates it.  Returns the server's representation of the oAuthProvider, and an error, if there is any.
func (c *oAuthProviders) Create(oAuthProvider *v1.OAuthProvider) (result *v1.OAuthProvider, err error) {
	result = &v1.OAuthProvider{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("oauthproviders").
		Body(oAuthProvider).
		Do().
		Into(result)
	return
}

// Update takes the representation of a oAuthProvider and updates it. Returns the server's representation of the oAuthProvider, and an error, if there is any.
func (c *oAuthProviders) Update(oAuthProvider *v1.OAuthProvider) (result *v1.OAuthProvider, err error) {
	result = &v1.OAuthProvider{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("oauthproviders").
		Name(oAuthProvider.Name).
		Body(oAuthProvider).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *oAuthProviders) UpdateStatus(oAuthProvider *v1.OAuthProvider) (result *v1.OAuthProvider, err error) {
	result = &v1.OAuthProvider{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("oauthproviders").
		Name(oAuthProvider.Name).
		SubResource("status").
		Body(oAuthProvider).
		Do().
		Into(result)
	return
}

// Delete takes name of the oAuthProvider and deletes it. Returns an error if one occurs.
func (c *oAuthProviders) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("oauthproviders").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *oAuthProviders) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("oauthproviders").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched oAuthProvider.
func (c *oAuthProviders) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.OAuthProvider, err error) {
	result = &v1.OAuthProvider{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("oauthproviders").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
