/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	configv1 "github.com/appvia/hub-apis/pkg/apis/config/v1"
	versioned "github.com/appvia/hub-apis/pkg/client/clientset/versioned"
	internalinterfaces "github.com/appvia/hub-apis/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/appvia/hub-apis/pkg/client/listers/config/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClassInstanceListInformer provides access to a shared informer and lister for
// ClassInstanceLists.
type ClassInstanceListInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ClassInstanceListLister
}

type classInstanceListInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClassInstanceListInformer constructs a new informer for ClassInstanceList type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClassInstanceListInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClassInstanceListInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredClassInstanceListInformer constructs a new informer for ClassInstanceList type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClassInstanceListInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ConfigV1().ClassInstanceLists().List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ConfigV1().ClassInstanceLists().Watch(options)
			},
		},
		&configv1.ClassInstanceList{},
		resyncPeriod,
		indexers,
	)
}

func (f *classInstanceListInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClassInstanceListInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *classInstanceListInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&configv1.ClassInstanceList{}, f.defaultInformer)
}

func (f *classInstanceListInformer) Lister() v1.ClassInstanceListLister {
	return v1.NewClassInstanceListLister(f.Informer().GetIndexer())
}
