/*
Copyright 2019 Rohith Jayawardene <info@appvia.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	orgv1 "github.com/appvia/hub-apis/pkg/apis/org/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTeamInvitations implements TeamInvitationInterface
type FakeTeamInvitations struct {
	Fake *FakeOrgV1
	ns   string
}

var teaminvitationsResource = schema.GroupVersionResource{Group: "org.hub.appvia.io", Version: "v1", Resource: "teaminvitations"}

var teaminvitationsKind = schema.GroupVersionKind{Group: "org.hub.appvia.io", Version: "v1", Kind: "TeamInvitation"}

// Get takes name of the teamInvitation, and returns the corresponding teamInvitation object, and an error if there is any.
func (c *FakeTeamInvitations) Get(name string, options v1.GetOptions) (result *orgv1.TeamInvitation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(teaminvitationsResource, c.ns, name), &orgv1.TeamInvitation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*orgv1.TeamInvitation), err
}

// List takes label and field selectors, and returns the list of TeamInvitations that match those selectors.
func (c *FakeTeamInvitations) List(opts v1.ListOptions) (result *orgv1.TeamInvitationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(teaminvitationsResource, teaminvitationsKind, c.ns, opts), &orgv1.TeamInvitationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &orgv1.TeamInvitationList{ListMeta: obj.(*orgv1.TeamInvitationList).ListMeta}
	for _, item := range obj.(*orgv1.TeamInvitationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested teamInvitations.
func (c *FakeTeamInvitations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(teaminvitationsResource, c.ns, opts))

}

// Create takes the representation of a teamInvitation and creates it.  Returns the server's representation of the teamInvitation, and an error, if there is any.
func (c *FakeTeamInvitations) Create(teamInvitation *orgv1.TeamInvitation) (result *orgv1.TeamInvitation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(teaminvitationsResource, c.ns, teamInvitation), &orgv1.TeamInvitation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*orgv1.TeamInvitation), err
}

// Update takes the representation of a teamInvitation and updates it. Returns the server's representation of the teamInvitation, and an error, if there is any.
func (c *FakeTeamInvitations) Update(teamInvitation *orgv1.TeamInvitation) (result *orgv1.TeamInvitation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(teaminvitationsResource, c.ns, teamInvitation), &orgv1.TeamInvitation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*orgv1.TeamInvitation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTeamInvitations) UpdateStatus(teamInvitation *orgv1.TeamInvitation) (*orgv1.TeamInvitation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(teaminvitationsResource, "status", c.ns, teamInvitation), &orgv1.TeamInvitation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*orgv1.TeamInvitation), err
}

// Delete takes name of the teamInvitation and deletes it. Returns an error if one occurs.
func (c *FakeTeamInvitations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(teaminvitationsResource, c.ns, name), &orgv1.TeamInvitation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTeamInvitations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(teaminvitationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &orgv1.TeamInvitationList{})
	return err
}

// Patch applies the patch and returns the patched teamInvitation.
func (c *FakeTeamInvitations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *orgv1.TeamInvitation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(teaminvitationsResource, c.ns, name, pt, data, subresources...), &orgv1.TeamInvitation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*orgv1.TeamInvitation), err
}
